name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup rust
        run: rustup target add x86_64-unknown-linux-musl
      - name: test
        run: cargo test --all-targets
      - name: clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets -- -D warnings
